#!/bin/bash

# Instalación de grive en Debian 8:
# http://informatica-fcien.blogspot.com/2015/08/instalar-grive2-en-debian-8-grive-en.html

FICHCONFGRIVE="/etc/default/vx-variables-grive2"
CMD_GET="crudini --get ${FICHCONFGRIVE} Confgrive"
# DIRBINDGRIVE="/var/nfs/privado/Drive"
DIRBINDGRIVE="$(${CMD_GET} grive2_default_dir 2> /dev/null)"
GRIVE_COMMAND_WITH_PATH=/usr/local/bin/grive    # Path to your grive binary, change to match your system
GDRIVE_PATH="${DIRBINDGRIVE}"         # Path to the folder that you want to be synced
TIMEOUT=60              # Timeout time in seconds, for periodic syncs. Nicely pointed out by ivanmacx

# El Timeout establece el tiempo que habiendo transcurrido sin detectar ningún cambio termina el comando inotifywait
while true ; do
    inotifywait -t $TIMEOUT -e modify -e move -e create -e delete -r $GDRIVE_PATH
    cd $GDRIVE_PATH && $GRIVE_COMMAND_WITH_PATH
done